#!/usr/bin/env php
<?php

require "vendor/autoload.php";

use Indatus\Callbot\Config;
use Symfony\Component\Console\Application;
use Indatus\Callbot\Commands\CallMultiCommand;
use Indatus\Callbot\Commands\CallSingleCommand;
use Indatus\Callbot\Commands\CallResultsCommand;
use Indatus\Callbot\Factories\FileStoreFactory;
use Indatus\Callbot\Factories\CallServiceFactory;
use Indatus\Callbot\Factories\ScriptGeneratorFactory;

$application = new Application;

$application->add(
    new CallSingleCommand(
        new CallServiceFactory(new Config),
        new FileStoreFactory(new Config),
        new Config
    )
);

$application->add(
    new CallMultiCommand(
        new CallServiceFactory(new Config),
        new FileStoreFactory(new Config),
        new Config
    )
);

$application->add(
    new CallResultsCommand(
        new CallServiceFactory(new Config),
        new FileStoreFactory(new Config),
        new Config
    )
);

$application->run();
