<?php

// Twilio credentials
define('TW_ACCOUNT_SID', 'XXXXXXXXXXXXXXXXX');
define('TW_AUTH_TOKEN', 'XXXXXXXXXXXXXXXXX');
define('TW_SOURCE_PHONE', '+15551234567');

// AWS credentials
define('AWS_ACCESS_KEY', 'XXXXXXXXXXXXXXXXX');
define('AWS_SECRET_KEY', 'XXXXXXXXXXXXXXXXX');