#!/usr/bin/env php
<?php

require_once "vendor/autoload.php";

use Symfony\Component\Console\Application;
use Indatus\Gopher\Commands\CallMultiCommand;
use Indatus\Gopher\Commands\CallSingleCommand;
use Indatus\Gopher\Commands\CallDetailsCommand;
use Indatus\Gopher\Factories\FileSystemFactory;
use Indatus\Gopher\Factories\CallServiceFactory;
use Indatus\Gopher\Factories\ResultsHandlerFactory;

$application = new Application;

$application->add(
    new CallSingleCommand(
        new CallServiceFactory,
        new FileSystemFactory,
        new ResultsHandlerFactory
    )
);

$application->add(
    new CallMultiCommand(
        new CallServiceFactory,
        new FileSystemFactory,
        new ResultsHandlerFactory
    )
);

$application->add(
    new CallDetailsCommand(
        new CallServiceFactory,
        new FileSystemFactory,
        new ResultsHandlerFactory
    )
);

$application->run();
